name: AEMY Lint CSS
on:
  pull_request:
    types: [labeled]

jobs:
  lint_css_job:
    name: Lint CSS
    runs-on: ubuntu-latest
    if: github.event.label.name == 'aemy-lint-css'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: npm install
    - run: npm run lint:css -- --fix
    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-commit: Apply css lint fixes"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: aemy-lint-css
